#!/bin/bash

WRAPPER_PATH=$(readlink -f /usr/bin/google-chrome-stable)
BASE_PATH="$WRAPPER_PATH-base"
mv "$WRAPPER_PATH" "$BASE_PATH"

cat > "$WRAPPER_PATH" <<_EOF
#!/bin/bash
# --disable-web-security
# Note: exec -a below is a bashism.
export DISPLAY=:0 && exec -a "\$0" "$BASE_PATH" --disable-gpu --no-sandbox "\$@"
_EOF
chmod +x "$WRAPPER_PATH"